In [3]:
import numpy as np

### 1) Basic Array Creation

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [11]:
a = [1,2,3.5,False]
a

[1, 2, 3.5, False]

In [12]:
np.array(a)

array([1. , 2. , 3.5, 0. ])

In [15]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 2) Array Generation function

In [18]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr = np.zeros(6)
arr

arr = np.zeros((4,8)) # 4 Rows and 8 Columns
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
arr = np.linspace(1,10,100)
arr

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

### 3) Random Generation Function

In [26]:
np.random.rand(100)

array([0.11049835, 0.50093832, 0.33132236, 0.2303294 , 0.49845628,
       0.42331717, 0.51292237, 0.89580396, 0.62572775, 0.56109911,
       0.26767211, 0.42050407, 0.81704327, 0.98093246, 0.02706197,
       0.54509043, 0.55724997, 0.13171629, 0.60910659, 0.24177585,
       0.47946173, 0.98528752, 0.10850876, 0.26604259, 0.70135446,
       0.53314994, 0.74799424, 0.05401188, 0.77286994, 0.93815375,
       0.64646431, 0.92133218, 0.18158583, 0.37036055, 0.72288583,
       0.39391742, 0.52297104, 0.5297849 , 0.76191324, 0.23724954,
       0.70026862, 0.52931473, 0.96061772, 0.94174833, 0.82414432,
       0.26866574, 0.61709261, 0.82754353, 0.16261749, 0.32947438,
       0.04748041, 0.12059718, 0.70880568, 0.16344854, 0.78131079,
       0.22249692, 0.07283282, 0.35736441, 0.9855059 , 0.64988997,
       0.00117512, 0.68279977, 0.9484642 , 0.04601909, 0.8713714 ,
       0.54461016, 0.3668921 , 0.46975442, 0.90837753, 0.73413913,
       0.44249967, 0.70524709, 0.35998981, 0.07248869, 0.19957

In [32]:
np.random.randn(10)

array([-0.61303658,  0.40647302,  1.53865884,  0.3275816 , -0.6630886 ,
        0.32731184,  2.4258251 , -1.5362747 , -1.7520474 ,  2.21655033])