In [3]:
import numpy as np

### 1) Basic Array Creation

In [6]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [11]:
a = [1,2,3.5,False]
a

[1, 2, 3.5, False]

In [12]:
np.array(a)

array([1. , 2. , 3.5, 0. ])

In [15]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### 2) Array Generation function

In [18]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
arr = np.zeros(6)
arr

arr = np.zeros((4,8)) # 4 Rows and 8 Columns
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr = np.linspace(1,10